[project]
name = "MentalHealthBot"
version = "v1"
dependencies = ["openai","importlib", "pathlib", "os", "requests", "json", "sys", "date"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["scheduleParser"]